### ISSUE TITLE
How to document returning data?

### ISSUE THREAD

**Issue by olegantonyan** [Apipie/apipie-rails#372] opened 2015-06-14 18:17 UTC
It's clear how to describe POST/PATCH actions with _input_ parameters. But how should I write API documentation for _output_ JSON data? There is nothing about documenting what is returned by show/index actions. Sure I can copy and paste jbuilder templates to `description` block, but it feels not very good.

**Comment by saneshark** [comment] 2015-06-14 20:15
@FlySnake I just used params for POST and PATCH as well, but it's assumed that those params would be sent as part of a JSON request body as opposed to form-urlencoded parameters. As for the generated examples, those can be generated via tests automatically, even a simple one line request spec will do the trick -- there's some instructions in the README.

**Comment by FlySnake** [comment] 2015-06-15 03:55
Thank you @saneshark. However, it's still not clear for me. I can provide `example` with an example of returning JSON data. But how do I describe what each field in that JSON means?
```
  api!
  description 'Get all news sorted by date'
  example <<-EOS
  {
    "data":
    [
      {
        "date":"01.01.1970",
        "title":"Update",
        "body":"Free beer"
      },
    ]
  }
  EOS
  def index
    ....
  end
```
Very simple example, but what if this is rather complex object? Where should I put description for each field?

**Comment by saneshark** [comment] 2015-06-15 21:48
Yea, I see what you mean. I think generally speaking JSON consumer should have some understanding of the underlying data that will be returned, but thats not always the case. I'm trying to think the best mechanism on how something like this would be handled -- ideally something along the lines of JSON spec, but with comments. I don't think there is a mechanism to provide descriptions for JSON output available currently - at best you could use the short description and create Markdown and load it accordingly from your docs folder.

:+1: for adding this as a feature though, one in which it can automatically interpret based on using some rspec suite specifically tailored for testing JSON output to match some spec.

**Comment by Pajk** [comment] 2015-12-14 00:25
@olegantonyan This feature is not present but it's actually good point and should not be very hard to add it. It's quite common feature of other API documentation platforms/formats (eg. https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-response-section)

It should be possible to describe all response attributes in similar way as request params. 

I can imagine that `api_response` (`response` being too general) and `attribute` methods could be used for this purpose.

    api! 'Create user'
    param_group :user
    param :user, Hash do
      param :permalink, String
    end
    param :facts, Hash, :desc => "Additional optional facts about the user", :allow_nil => true
    api_response 'json' do
      attribute :id, Integer, desc: "User's unique id" 
      attribute :session_id, desc: "Session token"
    end
    def create; end

I would be happy to see a pull request with this feature:).

**Comment by techverx** [comment] 2016-09-09 18:54
@Pajk, Is there any update on this that how do we handle responses ?

Thanks

**Comment by Pajk** [comment] 2016-09-10 08:02
Nope. Do you plan to extend the DSL with something similar in the future @inecas?

**Comment by tstrachota** [comment] 2017-04-18 15:49
That would be very nice feature. I would be great if the description could be connected with the code that generates the output (e.g. rabl?). That way it would be much easier to track the changes and it would prevent developers from changing the output and forgetting to update docs.

**Comment by iNecas** [comment] 2018-01-02 11:16
Closing as duplicate of #273

**Closed by iNecas** 2018-01-02 11:16 UTC
Labels: rfe
