### ISSUE TITLE
document response object

### ISSUE THREAD

**Issue by trungpham** [Apipie/apipie-rails#321] opened 2015-01-08 22:15 UTC
is there a way to document the response object? it's just as important as the request object.

**Comment by iNecas** [comment] 2015-01-12 08:18
Not yet but I would be happy to review a patch that would introduce that.

**Comment by iNecas** [comment] 2015-01-19 13:44
Just noticed it's a duplicate of #273 Closing in favor of that request

**Closed by iNecas** 2015-01-19 13:44 UTC

**Comment by noctivityinc** [comment] 2015-09-26 19:08
+1  We need some kind of way to document in a table what the various response elements mean.  Its great to have the example, but without an explaination of the response object it's harder to use the API.
